services:
  - type: web
    name: document-analysis-api
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y build-essential libmupdf-dev libjpeg-dev zlib1g-dev libtesseract-dev && \
      pip install --upgrade pip setuptools wheel && \
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: us-east-1-aws
      - key: INDEX_NAME
        value: askllm
      - key: PORT
        value: 10000
    healthCheckPath: /health
