services:
  - type: web
    name: document-analysis-system
    env: python
    plan: starter  # Changed from free for better performance
    
    # Updated build command for Python 3.12.4 compatibility
    buildCommand: |
      # Set Python version
      python --version
      
      # Update system packages
      apt-get update && apt-get install -y \
        build-essential \
        libffi-dev \
        libssl-dev \
        python3-dev \
        pkg-config \
        libmupdf-dev \
        libjpeg-dev \
        zlib1g-dev \
        cmake \
        gcc \
        g++
      
      # Upgrade Python packaging tools
      pip install --upgrade pip setuptools wheel
      
      # Set Rust/Cargo environment for tokenizers
      export CARGO_HOME=/tmp/.cargo
      export CARGO_TARGET_DIR=/tmp/.cargo-target
      
      # Install dependencies with specific order for compatibility
      pip install --no-cache-dir torch==2.5.1 --index-url https://download.pytorch.org/whl/cpu
      pip install --no-cache-dir numpy==2.1.3
      pip install --no-cache-dir -r requirements.txt
      
      # Verify critical imports
      python -c "import torch; print('PyTorch:', torch.__version__)"
      python -c "import numpy; print('NumPy:', numpy.__version__)"
      python -c "import sentence_transformers; print('SentenceTransformers: OK')" || echo "SentenceTransformers: Will use fallback"
    
    startCommand: |
      python main.py
    
    # Environment variables
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      
      # API Keys (set these in Render dashboard)
      - key: GEMINI_API_KEY
        sync: false
      
      - key: PINECONE_API_KEY
        sync: false
      
      # Pinecone configuration
      - key: PINECONE_ENVIRONMENT
        value: us-east-1-aws
      
      - key: INDEX_NAME
        value: askllm
      
      # Server configuration
      - key: PORT
        value: 10000
      
      # Build optimization for Python 3.12
      - key: PYTHONUNBUFFERED
        value: "1"
      
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      
      # Rust/Cargo cache directories for tokenizers compilation
      - key: CARGO_HOME
        value: /tmp/.cargo
      
      - key: CARGO_TARGET_DIR
        value: /tmp/.cargo-target
      
      # PyTorch configuration for CPU-only deployment
      - key: TORCH_CUDA_ARCH_LIST
        value: ""
      
      - key: CUDA_VISIBLE_DEVICES
        value: ""
      
      # Memory optimization
      - key: MALLOC_ARENA_MAX
        value: "2"
      
      # Tokenizers parallelism (disable to avoid warnings)
      - key: TOKENIZERS_PARALLELISM
        value: "false"
    
    # Health check configuration
    healthCheckPath: /health
    
    # Auto-deploy settings
    autoDeploy: true
    
    # Build timeout (extended for Python 3.12 compilation)
    buildTimeout: 30m