services:
  - type: web
    name: ask-llm
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn scripts.main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: us-east-1-aws
      - key: INDEX_NAME
        value: askllm
